[package]
name = "ladefuchs-api"
version = "2.0.3"
edition = "2024"

[profile.release]
strip = "debuginfo"
opt-level = 3
debug = false

[dependencies]
thiserror = "2.0.12"
tokio = { version = "1.44.2", features = [
	"macros",
	"net",
	"fs",
	"rt-multi-thread",
	"time",
	"signal",
] }
sqlx = { version = "0.8.5", default-features = false, features = [
	"runtime-tokio-rustls",
	"postgres",
	"migrate",
	"macros",
	"chrono",
	"json",
	"uuid",
] }
reqwest = { version = "0.12.15", default-features = false, features = [
	"json",
	"rustls-tls",
] }
eyre = "0.6.12"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = { version = "1.0.140", features = ["raw_value"] }
axum = { version = "0.8.4", features = [
	"http2",
	"tower-log",
	"query",
	"macros",
] }
axum-extra = { version = "0.10.1", features = ["typed-header", "cookie"] }
headers = "0.4.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = [
	"env-filter",
	"json",
	"ansi",
	"time",
] }
uuid = { version = "1.16.0", features = ["serde", "v4", "v7"] }
envy = "0.4.2"
url = { version = "2.5.4", features = ["serde"] }
time = "0.3.41"
trace = "0.1.7"
tower-http = { version = "0.6.2", features = [
	"trace",
	"compression-deflate",
	"cors",
	"sensitive-headers",
	"fs",
] }
strum_macros = "0.27.1"
futures-util = "0.3.31"
mime = "0.3.17"
chrono = { version = "0.4.40", features = ["serde"] }
tower = "0.5.2"
hotwatch = "0.5.0"
blake3 = "1.8.2"
tree_magic_mini = { version = "3.1.6" }
regex = "1.11.1"
once_cell = "1.21.3"
tokio-util = { version = "0.7.15", features = ["io"] }
serde_with = { version = "3.12.0", features = ["chrono"] }
rand = "0.9.1"
bcrypt = "0.17.0"
paste = "1.0.15"
base64 = "0.22.1"
console-subscriber = "0.4.1"
jsonwebtoken = "9.3.1"
tower-cookies = "0.11.0"
async-trait = "0.1.88"
async-stream = "0.3.6"
celes = "2.6.0"
tokio-cron-scheduler = {version = "0.13.0", features = ["signal", "tracing-subscriber"]}
