-- Add down migration script here
create table tarif_image
(
    id integer generated by default as identity
        primary key,
    file_path text not null unique,
    checksum text not null,
    mime_type text not null,
    updated timestamptz NOT NULL DEFAULT now()
);

-- add image reference to image
alter table tarif add column image integer references tarif_image(id) on delete set null;
alter table tarif add column url text;
alter table tarif add internal_name text default '' not null;

CREATE PROCEDURE internal_tarif_name()
    LANGUAGE plpgsql
AS $$
DECLARE
    row RECORD;
    BEGIN
        FOR row IN SELECT id, legacy_id as legacy FROM msp LOOP
            update tarif
            set internal_name = row.legacy
            where msp_id = row.id;
        END LOOP;
    END;
$$;

call internal_tarif_name();

-- fix tarif internal names
delete from tarif
where relationship_id = '18b85e93-0ade-4ad9-a6f6-bdf07f7cf816' 
or relationship_id =  'de1d9cd0-5593-4c63-bcfc-b92f6b79f074';

update tarif
set internal_name = 'adac'
where relationship_id = '36c2017a-097a-4072-9a58-6ef904b6173d';

update tarif
set internal_name = 'hundai'
where relationship_id = 'a67a4af3-aca2-4d9e-9b2c-91a0156e0950';

update tarif
set internal_name = 'smoov'
where relationship_id = '616c2f41-ea6d-4a96-806f-a49f719a7ca7';

update tarif
set internal_name = 'oeamtc'
where relationship_id = '23aeeed8-e973-4ffd-9f16-1996d259d791';

update tarif
set internal_name = 'elli'
where relationship_id = '91447011-4543-4509-b7b9-2aa90aa3ba63';

update tarif
set internal_name = 'dew21'
where relationship_id = '1ea846df-919d-4786-9f7e-d26ec7d54650';

update tarif
set internal_name = 'dew21'
where relationship_id = '1ea846df-919d-4786-9f7e-d26ec7d54650';

update tarif
set internal_name = 'maingau'
where relationship_id = '8fdeb6b4-2d72-4cff-87d8-081fa0ac4688';

update tarif
set internal_name = 'sw_buehl'
where relationship_id = 'd78dd6c4-7401-4dbd-9114-f15e86630b74';

update tarif
set internal_name = 'stromfahrer'
where relationship_id = 'a15898c9-8aea-4d06-a734-50342a6aa980';

update tarif
set internal_name = 'ewe_go'
where relationship_id = '35822dd4-6889-4015-b9e5-e9aac838e516';

update tarif
set internal_name = 'ewe_go'
where relationship_id = '35822dd4-6889-4015-b9e5-e9aac838e516';

update tarif
set internal_name = 'sw_buehl'
where relationship_id = 'd78dd6c4-7401-4dbd-9114-f15e86630b74';

update tarif
set internal_name = 'sw_kaiserslautern'
where relationship_id = '175a2184-39a7-4e7f-85d1-a8f5fa9a7347';

update tarif
set internal_name = 'wechargefree'
where relationship_id = 'b30b35b7-a3ae-4ffe-b8df-6cbe338bfe70';

update tarif
set internal_name = 'swm'
where relationship_id = '0f0b6d38-14fb-4ffd-ac71-e83d5a368278';

update tarif
set internal_name = 'sw_ladeverbund'
where relationship_id = '7e688c80-b312-48e0-aed8-6aba57439de4';

update tarif
set internal_name = 'sw_badenbaden'
where relationship_id = '0241bab6-2185-44e4-b010-4a893544133b';

update tarif
set internal_name = 'sw_gew'
where relationship_id = '83a608b4-ba19-4740-9f9a-61aee1f2aeda';

update tarif
set internal_name = 'sw_ingolstadt'
where relationship_id = '0efd4ffd-cc9d-4ddd-8a74-5dca40728ff4';

update tarif
set internal_name = 'evway'
where relationship_id = 'c9fa56cc-6365-467c-b46f-eba2d13f9849';

update tarif
set internal_name = 'lichtblick'
where relationship_id = '21a10712-bd10-4f91-89b6-15d20890a0d0';

update tarif
set internal_name = 'hyundai', alternative_operator_name = 'hyundai'
where relationship_id = 'a67a4af3-aca2-4d9e-9b2c-91a0156e0950';

update tarif
set internal_name = 'shell_recharge'
where relationship_id = 'cbe781a1-c16e-4af0-890a-b5f5943b6b77';

update tarif
set internal_name = 'alperia-neogy'
where relationship_id = '6ce0ce3f-cf7e-4bb4-841e-86030f1c6274';

update tarif
set internal_name = 'loewenladen'
where relationship_id = 'f95c113a-f9c4-4857-ae3a-086865af37b9';

update tarif
set internal_name = 'gpjoule'
where relationship_id = 'a7367fab-56b2-404b-858d-e541b4c61fc2';

update tarif
set internal_name = 'northe'
where relationship_id = '24803992-59f3-4589-b149-5249d9e5ade0';

update tarif
set internal_name = 'enelx'
where relationship_id = '7221b94b-4128-470e-befd-9f96ada009ef';

update tarif
set internal_name = 'ewp-echtmobil'
where relationship_id = '7a42726c-5a39-4a30-9299-d3945210149e';

update tarif
set internal_name = 'ev_rodaustrom'
where relationship_id = '6640c45d-0704-4adb-9a7a-a1afea17b3eb';

update tarif
set internal_name = 'epower'
where relationship_id = '23aeeed8-e973-4ffd-9f16-1996d259d791';

-- stadtwerke_tubingen
update tarif
set internal_name = 'swt'
where relationship_id = '599dce51-072a-4265-b866-e5941491329a';


-- rename cpo newmotion -> shell recharge
update cpo
set name = 'shellrecharge', slug_name = 'Shell Recharge'
where network = 'fda62ff9-5ae7-4aca-8f50-2c224ae0c834'