-- Add up migration script here

CREATE TYPE ChargeType AS ENUM ('AC', 'DC');

create table cpo(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network UUID UNIQUE NOT NULL,
    name text UNIQUE NOT NULL CHECK (name <> ''),
    is_enabled boolean NOT NULL DEFAULT TRUE,
    slug_name text UNIQUE NOT NULL CHECK (name <> ''),
    extra json NOT NULL
);

CREATE TYPE VehicleType AS ENUM ('Car');

create table vehicle(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    uuid UUID UNIQUE NOT NULL, 
    name text UNIQUE NOT NULL,
    vehicle_type VehicleType not null DEFAULT 'Car'
);

create table msp(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    msp_id uuid UNIQUE NOT NULL,
    name text UNIQUE NOT NULL,
    is_enabled boolean NOT NULL DEFAULT TRUE
);

create table tarif(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    relationship_id uuid UNIQUE NOT NULL,
    msp_id int NOT NULL REFERENCES msp(id) ON DELETE CASCADE,
    vehicle_id int NOT NULL REFERENCES vehicle(id) ON DELETE CASCADE,
    slug_name text UNIQUE NOT NULL CHECK (slug_name <> ''),
    monhtly_fee double precision NOT NULL DEFAULT 0
);


create table charge_price(
    cpo_id int NOT NULL REFERENCES CPO(id),
    tarif_id int NOT NULL REFERENCES tarif(id),
    c_type ChargeType NOT NUll,
    PRIMARY KEY(cpo_id, tarif_id, c_type),
    price double precision NOT NULL DEFAULT 0,
    blocking_fee_start bigint NOT NULL DEFAULT 0,
    updated timestamptz NOT NULL DEFAULT now()
);

