-- Add up migration script here
alter table charge_price drop constraint charge_price_tarif_id_fkey;
alter table charge_price add constraint charge_price_tariff_id_fkey foreign key(tarif_id) references tariff(id) on delete cascade;


alter table tariff add column if not exists updated timestamptz NOT NULL DEFAULT now();
alter table tariff add column if not exists note text not null default '';

create table msp_cpo(
  id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  cpo_id int NOT NULL REFERENCES cpo(id) ON DELETE CASCADE,
  msp_id int NOT NULL REFERENCES msp(id) ON DELETE CASCADE,
  unique(cpo_id, msp_id)
);