-- Add up migration script here
create table link(
     id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     is_affiliate boolean NOT NULL DEFAULT false,
     source text not null CHECK (source <> '')
);

CREATE TYPE PlattformType AS ENUM ('IOS', 'Android', 'Web');

create table affiliate_state(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id int NOT NULL REFERENCES link(id) ON DELETE CASCADE,
    plattform PlattformType not null DEFAULT 'Web',
    visited timestamptz NOT NULL DEFAULT now()
);

create table link_banner(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pub_id uuid UNIQUE NOT NULL DEFAULT gen_random_uuid(),
    link_id int NOT NULL REFERENCES link(id) ON DELETE CASCADE,
    image_path text not null CHECK (image_path <> ''),
    high_priority boolean NOT NULL DEFAULT false,
    updated timestamptz NOT NULL DEFAULT now(),
    unique (link_id, image_path)
);

insert into link (source, is_affiliate) values('https://geld-fuer-eauto.de/ref/Ladefuchs', true);
insert into link (source, is_affiliate) values('https://shop.ladefuchs.app', false);
