-- Add up migration script here
alter table tariff_image add column soft_delete bool not null default false;
create table filter
(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    value text not null check ( value <> '' )
);
