-- Add up migration script here
create table if not exists cpo_cache(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cpo_id uuid UNIQUE NOT NULL,
    slug_name text NOT NULL CHECK (slug_name <> ''),
    url text,
    updated timestamptz NOT NULL DEFAULT now(),
    search tsvector NOT NULL default ''
);
