-- Add up migration script here
CREATE extension pg_trgm;

create table if not exists cpo_cache(
    id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    network uuid UNIQUE NOT NULL,
    slug_name text NOT NULL CHECK (slug_name <> ''),
    url text,
    updated timestamptz NOT NULL DEFAULT now(),
    search tsvector NOT NULL default ''
);


CREATE FUNCTION cpo_cache_tsvector() RETURNS trigger AS $$
begin
    new.search := setweight(to_tsvector(coalesce(new.slug_name,'')), 'A');
    return new;
end
$$ LANGUAGE plpgsql;

CREATE TRIGGER cpo_cache_tsvector_update BEFORE INSERT OR UPDATE
    ON cpo_cache FOR EACH ROW EXECUTE PROCEDURE cpo_cache_tsvector();

CREATE INDEX cpo_cache_index ON cpo_cache USING GIN(search);
