-- Add up migration script here
create table if not exists app_metrics(
    app_id uuid not null,
    platform platformtype not null DEFAULT 'IOS',
    visited timestamptz NOT NULL DEFAULT now(),
    version integer not null default 0,
	PRIMARY KEY(app_id, visited)
);

create table if not exists impression_banner(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_link int NOT NULL REFERENCES link_banner(id) ON DELETE CASCADE,
    platform platformtype not null DEFAULT 'IOS',
    visited timestamptz NOT NULL DEFAULT now()
);
