-- Add up migration script here


CREATE TYPE FEEDBACKKIND AS ENUM ('wrong_price', 'other');

CREATE TABLE IF NOT EXISTS FEEDBACK (
    ID INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    OPERATOR_ID INT NOT NULL REFERENCES TARIFF (ID) ON DELETE CASCADE,
    TARIFF_ID INT NOT NULL REFERENCES TARIFF (ID) ON DELETE CASCADE,
    LANGUAGE TEXT NOT NULL,
    KIND FEEDBACKKIND NOT NULL,
    NOTES TEXT NOT NULL,
    CONTEXT JSONB
);
