CREATE TABLE impression_banner_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banner_link INT NOT NULL REFERENCES link_banner(id) ON DELETE CASCADE ON UPDATE CASCADE,
    platform platformtype NOT NULL,
    day DATE NOT NULL DEFAULT CURRENT_DATE,
    count INT NOT NULL DEFAULT 1,
    UNIQUE (banner_link, platform, day)
) WITH (fillfactor = 80);

CREATE TABLE affiliate_statistic_daily (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    link_id INT NOT NULL REFERENCES link(id) ON DELETE CASCADE,
    link_banner_id INT REFERENCES link_banner(id) ON DELETE CASCADE ON UPDATE CASCADE,
    platform platformtype NOT NULL,
    day DATE NOT NULL DEFAULT CURRENT_DATE,
    count INT NOT NULL DEFAULT 1,
    UNIQUE NULLS NOT DISTINCT (link_id, link_banner_id, platform, day)
) WITH (fillfactor = 80);

CREATE OR REPLACE FUNCTION trg_impression_banner_daily()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO impression_banner_daily (banner_link, platform, day, count)
    VALUES (NEW.banner_link, NEW.platform, NEW.visited::date, 1)
    ON CONFLICT (banner_link, platform, day)
    DO UPDATE SET count = impression_banner_daily.count + 1;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER impression_banner_daily_trigger
AFTER INSERT ON impression_banner
FOR EACH ROW EXECUTE FUNCTION trg_impression_banner_daily();

CREATE OR REPLACE FUNCTION trg_affiliate_statistic_daily()
RETURNS TRIGGER AS $$
BEGIN
    INSERT INTO affiliate_statistic_daily (link_id, link_banner_id, platform, day, count)
    VALUES (NEW.link_id, NEW.link_banner_id, NEW.platform, NEW.visited::date, 1)
    ON CONFLICT (link_id, link_banner_id, platform, day)
    DO UPDATE SET count = affiliate_statistic_daily.count + 1;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER affiliate_statistic_daily_trigger
AFTER INSERT ON affiliate_statistic
FOR EACH ROW EXECUTE FUNCTION trg_affiliate_statistic_daily();

INSERT INTO impression_banner_daily (banner_link, platform, day, count)
	SELECT banner_link, platform, visited::date, COUNT(*)
	FROM impression_banner
	GROUP BY banner_link, platform, visited::date;

INSERT INTO affiliate_statistic_daily (link_id, link_banner_id, platform, day, count)
	SELECT link_id, link_banner_id, platform, visited::date, COUNT(*)
	FROM affiliate_statistic
	GROUP BY link_id, link_banner_id, platform, visited::date;
