openapi: "3.0.3"
info:
  version: "1.0"
  description: |
    This is the Ladefuchs API that provides the data for the Android and IOS app. It caches daily the current charge prices from the [Chargeprice API](https://github.com/chargeprice/chargeprice-api-docs). In terms of security, this API uses the Bearer Authentication.  
    Every request has to include a valid token in the request header. Internally this API uses the [Chargeprice API](https://github.com/chargeprice/chargeprice-api-docs), this means that only a selected group can use this API. Keep this token privately and **do not expose** your token to the public.
  title: Ladefuchs API
  license:
    name: MIT
servers:
  - url: "{protocol}://api.ladefuchs.app"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
  - url: "{protocol}://beta.api.ladefuchs.app"
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
tags:
  - name: cards
    description: The charge prices
  - name: operators
    description: All operators who may be needed later to retrieve the prices
  - name: images
    description: All about images
paths:
  /operators/{mode}:
    get:
      tags:
        - operators
      description: Returns a list of all available operators.
      summary: "A list of operators"
      parameters:
        - in: path
          name: mode
          required: true
          schema:
            type: string
            enum: ["all", "enabled", "disabled"]
      responses:
        200:
          description: Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Operator"
        400:
          $ref: "#/components/responses/BadRequestError"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          $ref: "#/components/responses/InternalError"
  /v2/operators/{mode}:
    get:
      tags:
        - operators
      description: Returns a list of all available operators and there supported charge type fields.
      summary: "A list of operators"
      parameters:
        - in: path
          name: mode
          required: true
          schema:
            type: string
            enum: ["all", "enabled", "disabled"]
      responses:
        200:
          description: Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/OperatorV2"
        400:
          $ref: "#/components/responses/BadRequestError"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          $ref: "#/components/responses/InternalError"
  /cards/{country}/{operator}/{type}:
    get:
      tags:
        - "cards"
      summary: A list of charge prices Version 1
      description: "Returns a charge price list from that specific CPO and that specific current type."
      parameters:
        - $ref: "#/components/parameters/country"
        - $ref: "#/components/parameters/operator"
        - $ref: "#/components/parameters/type"
      responses:
        200:
          description: Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Card"
        400:
          $ref: "#/components/responses/BadRequestError"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          $ref: "#/components/responses/InternalError"
  /v2/cards/{country}/{operator}/{type}:
    get:
      tags:
        - "cards"
      summary: A list of charge prices Version 2
      description: |
        Returns a charge price list from that specific CPO and that specific current type. The Version 3 now also includes the `monthly_fee` as part of the JSON response.
      parameters:
        - $ref: "#/components/parameters/country"
        - $ref: "#/components/parameters/operator"
        - $ref: "#/components/parameters/type"
      responses:
        200:
          description: Description
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/CardV2"
        400:
          $ref: "#/components/responses/BadRequestError"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          $ref: "#/components/responses/InternalError"
  /img/cards:
    get:
      tags:
        - "images"
      summary: All available images
      responses:
        200:
          description: Description
          content:
            application/json:
              schema:
                type: array 
                items:
                  $ref: "#/components/schemas/CardImage"
        401:
          $ref: "#/components/responses/UnauthorizedError"
        500:
          $ref: "#/components/responses/InternalError"
                  
  /img/cards/{image_checksum}:
    get:
      tags:
        - "images"
      summary: Image for a specific card 
      parameters:
          - $ref: "#/components/parameters/image_checksum"
      description: |
        Returns the image based on the has of the file. The filename is 
      responses:
        200:
          description: Description
          headers: 
            Content-Type:
              description: The guessed MIME-Typ
              schema:
                type:
                  string
                example: image/jpeg
            Content-Disposition:
              description: The file name
              schema:
                type:
                  string
                example: attachment; filename="card_mvv_emotion.jpg"
          content:
            image/jpeg:
              schema: 
                type: string
            image/png:
              schema: 
                type: string
            image/svg:
              schema: 
                type: string
            image/gif:
              schema: 
                type: string
        401:
          $ref: "#/components/responses/UnauthorizedError"
        404:
          $ref: "#/components/responses/ResourceNotFound"
        500:
          $ref: "#/components/responses/InternalError"
components:
  schemas:
    Operator:
      type: object
      properties:
        identifier:
          type: string
          example: cpo-fastned
        displayName:
          type: string
          example: Fastned
        name:
          type: string
          example: fastned
      required:
        - name
        - displayName
        - identifier
    OperatorV2:
      allOf:
        - $ref: "#/components/schemas/Operator"
        - type: object
      properties:
        identifier:
          type: string
          format: uuid
          example: cdb15b63-1e05-4621-bdf6-8a6bf4330375
        types:
          type: array
          items:
            type: string
            enum: ["ac", "dc"]
          example: ["ac", "dc"]
      required:
        - types
    Card:
      type: object
      properties:
        identifier:
          type: string
          example: mvv_emotion
        name:
          type: string
          example: MVV eMotion
        provider:
          type: string
          example: MVV eMotion
        price:
          type: number
          format: double
          example: 0.39
        updated:
          type: integer
          format: int64
          example: 1641938519
      required:
        - identifier
        - name
        - provider
        - price
        - updated
    CardV2:
      type: object
      properties:
        identifier:
          type: string
          format: uuid
          example: 97960a25-8009-4250-8e61-b40651e2be99
        blocking_fee_start:
          type: integer
          format: int64
          example: 240
        image:
          type: string
          format: uri
          nullable: true
          example: "https://api.ladefuchs/images/card/559e1bae96b41b3903232e3dc8e0affbdfe758eea70a6125d5e9d094ad48b4e7"
        monthly_fee:
          type: number
          format: double
          example: 0
        name:
          type: string
          example: MVV eMotion
        provider:
          type: string
          example: MVV eMotion
        price:
          type: number
          format: double
          example: 0.39
        url:
          type: string
          format: uri
          nullable: true
          example: "https://api.chargeprice.app/v1/affiliate_redirect?app_id=08f2df6f-cbc5-4d61-b867-b7897ed88059&company_id=63567923-e4e1-4913-a03b-e86583b339fa&url=https%3A%2F%2Fmvv.chargecloud.de%2F"
        updated:
          type: integer
          format: int64
          example: 1641938519
      required:
        - identifier
        - blocking_fee_start
        - tarif_name
        - price
        - provider 
        - monthly_fee
        - updated
    CardImage:
      type: object
      properties:
        tariff_identifier:
          type: string
          format: uuid
          example: E-Mobil
        tariff_name:
          type: string
          example: 2a34aa70-e507-428d-91a2-38e6e4ef0a54
        checksum:
          type: string
          example: 01ae93454ea503d3fe20b4cc8444d43ba0ea4dd09608974de478cd570c9f96d3
        mime_type:
          type: string
          example: "image/jpeg"
        updated:
          type: integer
          format: int64
          example: 1655639702
        url: 
          type: string
          format: uri
          example: "https://api.ladefuchs/images/card/01ae93454ea503d3fe20b4cc8444d43ba0ea4dd09608974de478cd570c9f96d3"
      required:
        - tariff_identifier
        - checksum
        - mime_type
        - updated
        - url
    Error:
      type: object
      properties:
        status_code:
          description: HTTP response status codes
          type: integer
          example: 500
          minimum: 100
          maximum: 599
        reason:
          type: string
      required:
        - status_code
        - reason
        - blocking_fee_start
  parameters:
    country:
      in: path
      name: country
      required: true
      description: Only `de` is supported.
      schema:
        type: string
        example: de
    operator:
      in: path
      name: operator
      required: true
      example: 97960a25-8009-4250-8e61-b40651e2be99
      description: |
        The operator `name` case sensitivity or the public `UUID`.  
        For example `fastned` and `97960a25-8009-4250-8e61-b40651e2be99` will return the same result.
      schema:
        oneOf:
        - type: string
          format: uuid
          example: 97960a25-8009-4250-8e61-b40651e2be99
        - type: string
          example: fastned
    type:
      in: path
      name: type
      required: true
      description: Choose a current type.
      schema:
        type: string
        enum: ["ac", "dc"]
    image_checksum:
      in: path
      name: image_checksum
      description: The hash based of the file content
      required: true
      schema:
        type: string
        example: 559e1bae96b41b3903232e3dc8e0affbdfe758eea70a6125d5e9d094ad48b4e7
  securitySchemes:
    bearerAuth: # arbitrary name for the security scheme
      type: http
      scheme: bearer
  responses:
    BadRequestError:
      description: Wrong parameters were passed
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status_code: 400
            reason: "unknown variant enable, expected one of All, Enabled, Disabled"
    UnauthorizedError:
      description: Access token is missing or invalid
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status_code: 401
            reason: "wrong authorization token got: `xxxxxyyy`"
    ResourceNotFound:
      description: The Resource was not found
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status_code: 404
            reason: "The resource was not found"
    InternalError:
      description: An Unkown error has occured
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Error"
          example:
            status_code: 500
            reason: Internal server error
security:
  - bearerAuth: []
